### ISSUE TITLE
Progress Bar

### ISSUE THREAD

**Issue by drew-royster** [drew-royster/canvasFileSync-old#3]

**Comment by harryt04** [comment]
+1 on this progress bar. You looking to open source this? I'd love to contribute. We have a UVU [open source github group](https://github.com/UVU-Open-Source).

**Comment by drew-royster** [comment]
absolutely wanting as many contributors as possible!

**Comment by harryt04** [comment]
I'd love to help with the progress bar. After using it, I was gonna come suggest a progress bar but saw an open issue for it :D
